version: '3.1'

services:
  node01:
    image: cimadai/iroha:v1
    restart: always
    ports:
      - "50051:50051"
    environment:
      NODE_NAME: node01
    depends_on:
      - node01_redis
      - node01_pg
    volumes:
      - ./test_single_data/node/block-store:/tmp/block_store
      - ./test_single_data/node/iroha-status:/tmp/iroha-status
      - ./test_single_data/node/config:/opt/iroha/config
      - ./test_single_config:/tmp/iroha-config
    tty: true
    cap_add:
      - SYS_PTRACE
    command: "./bin/startup.sh"

  node01_redis:
    image: redis:3.2.8
    restart: always

  node01_pg:
    image: postgres:9.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always

